### ISSUE TITLE
Is it possible to edit the yml for an edit page title for a specific model?

### ISSUE THREAD

**Issue by rikkipitt** [sferik/rails_admin#2161]
Hi guys,

Is it possible to edit the "Edit page" title for a specific model? E.g. just for the User model...

``` yaml
en:
  admin:
    actions:
      edit:
        title: "Edit this but for User model only"
```

Rikki
