### ISSUE TITLE
How to i18n deletion page?

### ISSUE THREAD

**Issue by TangMonk** [sferik/rails_admin#2529]
![image](https://cloud.githubusercontent.com/assets/3498786/12315375/26a3609c-bab5-11e5-98f2-46e937251d89.png)

Notice the red circle in the avoid image, the `MaxiTime #1` should be `马戏时间 #1`, How to i18n it?

**Comment by tagliala** [comment]
model translation in the application .yml file?

eg: (translating activerecord `Product` model in Italian)

```yml
it:
  activerecord:
    models:
      product:
        one: Prodotto
        other: Prodotti
```
