### ISSUE TITLE
fields localized

### ISSUE THREAD

**Issue by saviokmua** [sferik/rails_admin#2927]
How to localized edit fields in rails_admin
i try
> config.model 'Course' do
>     edit do
>       field :name do
>       label 'Назва'
>     end
>   end
> 

it work very fine 
but it will take a very long time for me

How can I to add custom field name builder for all feilds like this?

> config.models do
    edit do
      fields do
        model = self.abstract_model.model_name.underscore
        field = self.name
        label I18n.t("#{model}.#{name}")
      end
    end
  end

**Comment by haslo** [comment]
RailsAdmin will use your ActiveRecord localizations:

```yml
de:
  activerecord:
    models:
      course: 'звичайно'
    attributes:
      course:
        name: 'Назва'
```
