### ISSUE TITLE
Datepicker not tracking seconds

### ISSUE THREAD

**Issue by nullvoids** [sferik/rails_admin#2963]
When updating a table with a datetime field, the datetime field always gets automatically updated because the datepicker is not tracking seconds. 

For example:
If you have a Users table with a date_of_birth column set to 12/1/2017 10:00:59 and you go on rails_admin and change the user's email, the date_of_birth column will automatically be changed to 12/1/2017 10:00:00

**Comment by sedubois** [comment]
I observe the same issue. Every time I edit an object, its datetime properties get updated with the seconds being stripped away. If I try to manually add the seconds in the date picker text box, they automatically disappear.

<img width="392" alt="Screenshot 2019-06-06 at 14 00 15" src="https://user-images.githubusercontent.com/4217871/59028206-a8ffff80-8863-11e9-95d1-9e4f69c16ab2.png">

Also I don't understand what controls the format of this date picker. I've seen other instances where the seconds did get shown (see the screenshot in https://github.com/sferik/rails_admin/issues/3134#issue-442612184).

Together with other date picker issues (#3134, #3140), it makes it quite difficult to use RailsAdmin to edit anything.

**Comment by sedubois** [comment]
This workaround seems to work (overwrite the time formatting to include seconds).

```yaml
# config/locales/rails.en.yml
en:
  time:
    formats:
      long: "%Y-%m-%d %H:%M:%S"

# config/locales/rails.fr.yml
fr:
  time:
    formats:
      long: "%Y-%m-%d %H:%M:%S"
```
