### ISSUE TITLE
Translation name list scope

### ISSUE THREAD

**Issue by matron-app** [sferik/rails_admin#3101]
I have 3 scopes of model
    list do
      scopes [nil, :cart, :filter, :yml]

How do i translate names of scopes to my locale?

**Comment by pciruzzi** [comment]
According to the `index.html.haml`:
https://github.com/sferik/rails_admin/blob/0a5a45757e730b12de2b76b72e8b711ade6874ee/app/views/rails_admin/main/index.html.haml#L66

You should place it under your `rails_admin.xx.yml`, like:
```yml
xx:
 admin:
    scopes:
      _all: "All"
      model_name:
        scope_name: "Scope name"
```
