### ISSUE TITLE
Datepicker don't show selected date properly

### ISSUE THREAD

**Issue by elsupergomez** [sferik/rails_admin#982]
In the form of a new object that have a field datetime, the datepicker for complete the field don't show selected date properly.

Ex: if I choose 15/02/2012 in spanish, the field show '15 15e febrero 15e 2012' instead of '15 de febrero de 2012'

When save the object for this example, the persisted value in the database is '15/02/2015' instead of '15/02/2012'

**Comment by dcabo** [comment]
Same here, with spanish. I fixed by adding the following lines to `locales/rails_admin.es.yml`:

      date:
        formats:
          default: ! '%d/%m/%Y'
          long: ! '%d %B %Y'
          short: ! '%d %b'

**Comment by mshibuya** [comment]
Closed by #2451.

**Comment by rodinux** [comment]
I have the same issue with French translation. I'd try the method of dcabo, but it didn't match as I configured all the application with I18n-fr... 
My default format: for datetime is :"%A %d %B %Y %Hh %M"

**Comment by rodinux** [comment]
I try to change, but it doesn't match : 

> no implicit conversion of nil into String
> Extracted source (around line #36):
> 
> 34
> 35
> 36
> 37
> 38
> 39
>               
> 
> 	
> 
>             when '%A'
>               english = ::I18n.t('date.day_names', locale: :en)
>               day_names.each_with_index { |d, i| date_string = date_string.gsub(/#{d}/, english[i]) }
>             when '%a'
>               english = ::I18n.t('date.abbr_day_names', locale: :en)
>               abbr_day_names.each_with_index { |d, i| date_string = date_string.gsub(/#{d}/, english[i]) }

**Comment by rodinux** [comment]
Ok, now it matches. But there is no hours in no hours anyway, just because of the function in 'lib/rails_admin/config/fields/type/datetime.rb' ? It is not possible to change this file ?

**Comment by rodinux** [comment]
I found a solution, for my views as I use a calendar which need the hours, I have added in my locales/fr.yml for the translalation 
```
  time:
    am: am
    date:
    formats:
      default: ! '%d/%m/%Y'
      long: ! '%d %B %Y'
      short: ! '%d %b'
      only_day: ! "%e"
      very_long: ! '%A %d %B %Y %Hh %M'
      day_names: [lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche]
      abbr_day_names: [lun, mar, mer, jeu, ven, sam, dim]
      month_names: [~, janvier, février, mars, avril, mai, juin, juillet, août, septembre, octobre, novembre, décembre]
      abbr_month_names: [~, janv, févr, mars, avr, mai, juin, juill, août, sept, oct, nov, déc]
      order:
        - :day
        - :month
        - :year
```
And I can use use 'my_field.hour, format: :very_long' to get the date ans the hour
